### PR TITLE
Allow multiple users to request image generation

### PR DESCRIPTION
**Pull request by mishalhossin**
Also updated todo.txt to add a new task ;)

### CODE REVIEW

**Comment by mishalhossin** [comment]
hehe

**Comment by mak448a** [comment]
I'll check it out

**Comment by mak448a** [comment]
What do you mean in todo.txt "Make chatbot with ai horde?"

**Comment by mak448a** [comment]
Also the bot still locks up.

**Comment by mak448a** [comment]
I'll look into it

**Comment by mak448a** [comment]
Screenshot_20230502_184429

**Comment by mak448a** [comment]
I'm looking into a solution

**Comment by mishalhossin** [comment]
> What do you mean in todo.txt "Make chatbot with ai horde?" Do you want me to integrate a chatbot in the discord bot?

Yes pls idk how to use ai horde tbh

**Comment by mak448a** [comment]
AI horde is just the thing that generates the images. If you want a chatbot, I could add GPT-Neo or some other text generator.

**Comment by mishalhossin** [comment]
> AI horde is just the thing that generates the images. If you want a chatbot, I could add GPT-Neo or some other text generator.

I have already made a bot using the GPT4FREE project https://github.com/mishalhossin/Discord-Chatbot-Gpt4Free but i wanna use the KoboldAI

**Comment by mishalhossin** [comment]
I think it also has a cli

**Comment by mak448a** [comment]
Okay, I'll make that an issue #6

**Comment by mak448a** [comment]
But multiple users can't use imagine at once still after I tested your version

**Pull request closed without merging**
