### PR TITLE
Add DALL-E and Pollinations

### PR DESCRIPTION
**Pull request by mishl-dev**
Wrote some code to add Dalle and Pollination image generation.

### CODE REVIEW

**Comment by mishalhossin** [comment]
Do you have discord ?

**Comment by mishalhossin** [comment]
@mak448a

**Comment by mishalhossin** [comment]
Added dalle and pollination

**Comment by mak448a** [comment]
> What is your discord ?

mak448a#9429

**Comment by mak448a** [comment]
You should consolidate all of the commands into /imagine and just have the model/service as a parameter in the command.

**Comment by mishalhossin** [comment]
> 

add it anyways we can do that later

**Comment by mak448a** [comment]
I'm not going to be merging pull requests for probably the next 1-2 weeks since I don't have my laptop.

**Comment by mishalhossin** [comment]
> By the way, how are you keeping the Replit alive? I'm planning on using Replit to host the bot, but uptimerobot seems to be broken.

I use https://script.google.com/home

with this script. Just run the create trigger function after putting your url

image


```
function fetchWebsite() {
  const url = 'https://asahigpt.mishal0legit.repl.co';
  const options = {
    method: 'get',
    timeoutInSeconds: 60
  };
  
  try {
    const response = UrlFetchApp.fetch(url, options);
    // Process the response if necessary
  } catch (error) {
    // Handle errors if necessary
  }
}

function createTrigger() {
  ScriptApp.newTrigger('fetchWebsite')
    .timeBased()
    .everyMinutes(1)
    .create();
}
```

**Comment by mak448a** [comment]
Not at home (won't be for around a week) but I'll try to test out your pull request on Replit

**Comment by mishalhossin** [comment]
> Not at home (won't be for around a week) but I'll try to test out your pull request on Replit

I'm not hosting the dalle endpoint rn cus openai has ratelimit even with 30 acesss keys

**Comment by mak448a** [comment]
Got it

**Comment by mak448a** [comment]
Agh too much of a pain, I'm just gonna wait till I get home lol

**Comment by mak448a** [comment]
Please rename bot.py to main.py

**Comment by mishalhossin** [comment]
> Please rename bot.py to main.py

okay

**Comment by mak448a** [comment]
LGTM!

**Pull request merged**
