### PR TITLE
Update bot.py

### PR DESCRIPTION
**Pull request by mishalhossin**

### CODE REVIEW

**Review by mishalhossin — COMMENTED** [review]
Idk wtf I'm doing

**Comment by mak448a** [comment]
Do you need any help with editing the code?

**Comment by mishalhossin** [comment]
> Do you need any help with editing the code?

No i got it to work in the end with help of [PhindAI](https://www.phind.com/)

**Comment by mishalhossin** [comment]
Also how to create slash command in python ?

**Comment by mak448a** [comment]
Check out this video for slash commands: https://www.youtube.com/watch?v=1geg9VTKhDE

**Comment by mishalhossin** [comment]
> Check out this video for slash commands: https://www.youtube.com/watch?v=1geg9VTKhDE

so slash still exist

**Comment by mak448a** [comment]
Yes.

**Comment by mishalhossin** [comment]
> Yes.

bruh i turned the command into normal command and used in my bot

**Pull request closed without merging**
